# Generated by Django 2.0 on 2018-01-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180112_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='wode',
            field=models.CharField(default=222, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
