# Generated by Django 2.0 on 2018-01-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180112_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='employee',
            field=models.ForeignKey(default=222, on_delete=django.db.models.deletion.CASCADE, to='blog.Employee'),
            preserve_default=False,
        ),
    ]
